# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = ["oss@fastly.com"]
description = ""
language = "go"
manifest_version = 2
name = "early-hints"

[local_server]
backends.httpme.url = "https://http-me.fastly.dev"
