# This file describes a Fastly Compute package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["oss@fastly.com"]
description = ""
language = "go"
manifest_version = 2
name = "add-or-remove-cookies"

[local_server]
backends.backend.url = "https://http-me.fastly.dev"
