name: Build Examples
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-examples:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          # Newest supported configuration
          - go-version: "1.25" # pairs with TinyGo 0.39.0
            tinygo-version: "0.39.0"
          # Oldest supported configuration
          - go-version: "1.23" # pairs with TinyGo 0.33.0
            tinygo-version: "0.33.0"

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build examples Go
        env:
          GOARCH: wasm
          GOOS: wasip1
        run: |
          for i in _examples/*/; do
            echo ${GITHUB_WORKSPACE}/$i
            cd ${GITHUB_WORKSPACE}/$i && go build -tags fastlyinternaldebug
          done

      - uses: acifani/setup-tinygo@v2
        with:
          tinygo-version: ${{ matrix.tinygo-version }}
          binaryen-version: "124"

      - name: Build examples TinyGo
        run: |
          for i in _examples/*/; do
            echo ${GITHUB_WORKSPACE}/$i
            cd ${GITHUB_WORKSPACE}/$i && tinygo build -target=wasip1 -tags fastlyinternaldebug
          done
