name: Build Examples
permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  get-go-version:
    uses: ./.github/workflows/reusable-go-version.yml

  build-examples:
    runs-on: ubuntu-latest
    needs: get-go-version
    strategy:
      matrix:
        include:
          # Newest supported configuration
          - go-version: ${{ needs.get-go-version.outputs.go-version-latest }}
            tinygo-version: "0.39.0"
          # Oldest supported configuration
          - go-version: ${{ needs.get-go-version.outputs.go-version-mod }}
            tinygo-version: "0.33.0"

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build examples Go
        env:
          GOARCH: wasm
          GOOS: wasip1
        run: |
          for i in _examples/*/; do
            echo ${GITHUB_WORKSPACE}/$i
            cd ${GITHUB_WORKSPACE}/$i && go build -tags fastlyinternaldebug
          done

      - uses: acifani/setup-tinygo@v2
        with:
          tinygo-version: ${{ matrix.tinygo-version }}
          binaryen-version: "124"

      - name: Build examples TinyGo
        run: |
          for i in _examples/*/; do
            echo ${GITHUB_WORKSPACE}/$i
            cd ${GITHUB_WORKSPACE}/$i && tinygo build -target=${GITHUB_WORKSPACE}/targets/fastly-compute-wasip1.json -tags fastlyinternaldebug
          done
