# Determines the Go version from go.mod and the latest available Go version.
name: Get Go Version
permissions:
  contents: read

on:
  workflow_call:
    outputs:
      go-version-mod:
        description: "The Go version specified in the go.mod file."
        value: ${{ jobs.go-mod-version.outputs.go-version-mod }}
      go-version-latest:
        description: "The latest available Go version."
        value: ${{ jobs.go-mod-version.outputs.go-version-latest }}

jobs:
  go-mod-version:
    runs-on: ubuntu-latest
    outputs:
      go-version-mod: ${{ steps.get-versions.outputs.mod }}
      go-version-latest: ${{ steps.get-versions.outputs.latest }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: "stable"
      - id: get-versions
        run: |
          output=$(go list -m -u go)
          mod_version=$(echo "$output" | awk '{print $2}')
          latest_version=$(echo "$output" | awk '{print $3}' | tr -d '[]')
          latest_version=${latest_version:-$mod_version}
          echo "mod=${mod_version}" >> $GITHUB_OUTPUT
          echo "latest=${latest_version}" >> $GITHUB_OUTPUT
      - name: Download Go modules
        run: go mod download
