name: Validate
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - id: setup-go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: vet
        run: go vet ./...

      - name: staticcheck
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          staticcheck ./...

      - name: nilness
        run: |
          go install golang.org/x/tools/go/analysis/passes/nilness/cmd/nilness@v0.36.0
          nilness ./...

      - name: ineffassign
        run: |
          go install github.com/gordonklaus/ineffassign@v0.2.0
          ineffassign ./...
