name: Validate
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - uses: ./.github/actions/install-tinygo
        with:
          tinygo-version: "0.35.0"

      - name: Print dependency versions
        run: |
          go version
          tinygo version

      - run: go vet ./...

      - name: staticcheck
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          staticcheck ./...

      - name: nilness
        run: |
          go install golang.org/x/tools/go/analysis/passes/nilness/cmd/nilness@master
          nilness ./...

      - name: ineffassign
        run: |
          go install github.com/gordonklaus/ineffassign@latest
          ineffassign ./...

      - name: Install viceroy
        run: make tools/viceroy

      - name: Run Tests
        run: make test
